language: python
env:
   - DJANGO='>=2.0,<2.1'
python:
   - "3.6"
matrix:
  exclude:
    - env: DJANGO='>=2.1'
      python: "2.7.13"
install:
   - pip install --upgrade pip
   - pip install -e .
   - pip install -r requirements/requirements_test.txt
   - pip install "Django${DJANGO}"
before_script:
    flake8 smsgateway/
script:
    pytest -v --capture=sys --cov=smsgateway/ smsgateway/ --cov-report term-missing:skip-covered
after_success:
    coveralls
