# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsgateway', '0002_auto_20170116_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedsms',
            name='priority',
            field=models.CharField(choices=[('1', 'high'), ('2', 'medium'), ('3', 'low'), ('9', 'deferred')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='sms',
            name='backend',
            field=models.CharField(db_index=True, default='unknown', max_length=32, verbose_name='backend'),
        ),
    ]
