PRIORITY_HIGH = '1'
PRIORITY_MEDIUM = '2'
PRIORITY_LOW = '3'
PRIORITY_DEFERRED = '99'

PRIORITIES = (
    (PRIORITY_HIGH,     'high'),
    (PRIORITY_MEDIUM,   'medium'),
    (PRIORITY_LOW,      'low'),
    (PRIORITY_DEFERRED, 'deferred'),
)
